name: OpenTofu Test Deployment

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
    INFRA_FOLDER_NAME: "Poc2_github_actions_integration/infra"  
    DEPLOYMENT_CONFIG_NAME: "dev2"

jobs:
  deploy:
    name: Deploy Infrastructure with OpenTofu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up OpenTofu
        uses: opentofu/setup-opentofu@v1
        # with:
        #   tofu_version: '1.9.0'  # Specify the desired OpenTofu version

      - name: Initialize OpenTofu
        run: |
          cd ${{ env.INFRA_FOLDER_NAME }}
          tofu init -var-file="../deployments/${{ env.DEPLOYMENT_CONFIG_NAME }}/terraform.tfvars" -reconfigure

    #   - name: Plan Infrastructure Changes
    #     run: |
    #       tofu plan -out=tfplan

    #   - name: Apply Infrastructure Changes
    #     if: github.ref == 'refs/heads/main'
    #     run: |
    #       tofu apply -auto-approve tfplan
