name: Test Workflow
env:
    ECR_REPOSITORY_NAME: ecr-ingest-service-dev

permissions:
  id-token: write
  contents: read

on:
  push:
  workflow_dispatch:
    inputs:
        AWS_ACCOUNT_ID:
          description: "The AWS account ID (optional, will use secret AWS_ACCOUNT_ID if not provided)"
          required: false
        AWS_REGION:
          description: "The AWS region (optional, will use secret AWS_REGION if not provided)"
          required: false    

jobs:
  build-and-push:
    name: Test Workflow Job
    runs-on: ubuntu-latest

    steps:
      - name: Set AWS_ACCOUNT_ID
        run: |
          if [ "${{ inputs.AWS_ACCOUNT_ID }}" ]; then
            echo "Using provided AWS_ACCOUNT_ID: ${{ inputs.AWS_ACCOUNT_ID }}"
            echo "aws_account_id=${{ inputs.AWS_ACCOUNT_ID }}" >> $GITHUB_ENV
          else
            echo "Using AWS_ACCOUNT_ID from secrets"
            echo "aws_account_id=${{ secrets.AWS_ACCOUNT_ID }}" >> $GITHUB_ENV
          fi
        id: set-aws-account-id

      - name: Set AWS_REGION
        run: |
          if [ "${{ inputs.AWS_REGION }}" ]; then
            echo "Using provided AWS_REGION: ${{ inputs.AWS_REGION }}"
            echo "aws_region=${{ inputs.AWS_REGION }}" >> $GITHUB_ENV
          else
            echo "Using AWS_REGION from secrets"
            echo "aws_region=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV
          fi
        id: set-aws-region

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        id: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.aws_account_id }}:role/role-opentofutest-github-actions-all
          role-session-name: github-actions-build
          aws-region: ${{ env.aws_region }}

      - name: List S3 Buckets
        run: |
          aws s3 ls